#!/usr/bin/env bash
# Regenerates the vendored Phosphor icon drawables.
#
# Phosphor is the cross-tier icon family (putio-design platforms/android/DESIGN.md).
# Source SVGs come from @phosphor-icons/core, pinned to the version the design
# cards load. Icons are drawn currentColor and tinted at the point of use.
#
# Icons land in the narrowest source set that uses them, so per-variant lint
# (UnusedResources, warningsAsErrors) stays clean: file-type glyphs and the
# nav icons shared with TV live in main, mobile-only nav art in mobile,
# TV-only art in tv.
set -euo pipefail

PHOSPHOR_VERSION="2.1.1"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# source-set drawable name phosphor-asset-path
ICONS=(
  "main ic_ph_folder_fill fill/folder-fill"
  "main ic_ph_file_fill fill/file-fill"
  "main ic_ph_file_audio_fill fill/file-audio-fill"
  "main ic_ph_file_video_fill fill/file-video-fill"
  "main ic_ph_file_image_fill fill/file-image-fill"
  "main ic_ph_file_zip_fill fill/file-zip-fill"
  "main ic_ph_file_pdf_fill fill/file-pdf-fill"
  "main ic_ph_file_text_fill fill/file-text-fill"
  "main ic_ph_file_code_fill fill/file-code-fill"
  "mobile ic_ph_folder regular/folder"
  "mobile ic_ph_arrow_left regular/arrow-left"
  "mobile ic_ph_sort_ascending regular/sort-ascending"
  "mobile ic_ph_magnifying_glass regular/magnifying-glass"
  "mobile ic_ph_magnifying_glass_fill fill/magnifying-glass-fill"
  "mobile ic_ph_arrow_circle_down regular/arrow-circle-down"
  "mobile ic_ph_arrow_circle_down_fill fill/arrow-circle-down-fill"
  "mobile ic_ph_user_circle regular/user-circle"
  "mobile ic_ph_user_circle_fill fill/user-circle-fill"
  "tv ic_ph_arrow_circle_down_fill fill/arrow-circle-down-fill"
  "tv ic_ph_gear_fill fill/gear-fill"
)

generated_paths=()
for entry in "${ICONS[@]}"; do
  read -r source_set name asset <<<"${entry}"
  out_dir="${REPO_ROOT}/app/src/${source_set}/res/drawable"
  output_path="${out_dir}/${name}.xml"
  generated_paths+=("${output_path}")
  mkdir -p "${out_dir}"
  url="https://unpkg.com/@phosphor-icons/core@${PHOSPHOR_VERSION}/assets/${asset}.svg"
  svg="$(curl -fsS --max-time 30 "${url}")"
  python3 - "$name" "$out_dir" "$source_set" <<PY
import re, sys
name, out_dir, source_set = sys.argv[1:4]
svg = """${svg}"""
paths = re.findall(r'\bd="([^"]+)"', svg)
if not paths:
    sys.exit(f"{name}: no path data found")
body = "\n".join(
    f'    <path\n        android:fillColor="#FF000000"\n        android:pathData="{d}" />'
    for d in paths
)
xml = f'''<!-- Phosphor {name.replace("ic_ph_", "").replace("_", "-")} v${PHOSPHOR_VERSION} (MIT). Generated by scripts/generate-icons.sh; do not edit. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="256"
    android:viewportHeight="256">
{body}
</vector>
'''
open(f"{out_dir}/{name}.xml", "w").write(xml)
print(f"wrote {source_set}/res/drawable/{name}.xml ({len(paths)} path)")
PY
done

# Remove only stale drawables previously generated by this script. This keeps
# source-set resource lint honest when an icon leaves the manifest above while
# preserving any hand-authored ic_ph_* asset.
for source_set in main mobile tv; do
  for existing in "${REPO_ROOT}/app/src/${source_set}/res/drawable"/ic_ph_*.xml; do
    [[ -e "${existing}" ]] || continue
    current=false
    for generated_path in "${generated_paths[@]}"; do
      if [[ "${existing}" == "${generated_path}" ]]; then
        current=true
        break
      fi
    done
    if [[ "${current}" == false ]] && grep -Fq "Generated by scripts/generate-icons.sh; do not edit." "${existing}"; then
      rm "${existing}"
      echo "removed ${existing#"${REPO_ROOT}/app/src/"}"
    fi
  done
done
