#!/usr/bin/env python3
"""Generate and check the repository's locked Phosphor vector drawables."""

from __future__ import annotations

import argparse
import base64
import hashlib
import hmac
import io
import json
import re
import tarfile
import urllib.request
import xml.etree.ElementTree as ElementTree
from dataclasses import dataclass
from pathlib import Path
from typing import NoReturn
from xml.sax.saxutils import escape


REPO_ROOT = Path(__file__).resolve().parent.parent
LOCK_PATH = REPO_ROOT / "design" / "phosphor-icons.lock.json"
GENERATED_MARKER = "Generated by scripts/generate-icons.sh; do not edit."
SOURCE_SETS = frozenset({"main", "mobile", "tv"})
SHA256_PATTERN = re.compile(r"[0-9a-f]{64}")
RESOURCE_PATTERN = re.compile(r"ic_ph_[a-z0-9_]+")
ASSET_PATTERN = re.compile(r"assets/(?:fill|regular)/[a-z0-9-]+\.svg")


@dataclass(frozen=True)
class PackageLock:
    name: str
    version: str
    tarball: str
    integrity: str


@dataclass(frozen=True)
class IconLock:
    source_set: str
    resource: str
    asset: str
    source_sha256: str
    output_sha256: str

    @property
    def output_path(self) -> Path:
        return (
            REPO_ROOT
            / "app"
            / "src"
            / self.source_set
            / "res"
            / "drawable"
            / f"{self.resource}.xml"
        )


def fail(message: str) -> NoReturn:
    raise SystemExit(f"generate-icons: {message}")


def require_string(value: object, field: str) -> str:
    if not isinstance(value, str) or not value:
        fail(f"{field} must be a non-empty string")
    return value


def require_sha256(value: object, field: str) -> str:
    digest = require_string(value, field)
    if SHA256_PATTERN.fullmatch(digest) is None:
        fail(f"{field} must be a lowercase SHA-256 digest")
    return digest


def require_object(value: object, field: str) -> dict[str, object]:
    if not isinstance(value, dict) or not all(isinstance(key, str) for key in value):
        fail(f"{field} must be an object")
    return value


def load_lock() -> tuple[PackageLock, tuple[IconLock, ...]]:
    try:
        document: object = json.loads(LOCK_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        fail(f"cannot read {LOCK_PATH.relative_to(REPO_ROOT)}: {error}")

    root = require_object(document, "lock")
    if set(root) != {"schemaVersion", "package", "icons"} or root["schemaVersion"] != 1:
        fail("lock must use schemaVersion 1 with package and icons fields")

    package_value = require_object(root["package"], "package")
    if set(package_value) != {"name", "version", "tarball", "integrity"}:
        fail("package lock fields do not match the schema")
    package = PackageLock(
        name=require_string(package_value["name"], "package.name"),
        version=require_string(package_value["version"], "package.version"),
        tarball=require_string(package_value["tarball"], "package.tarball"),
        integrity=require_string(package_value["integrity"], "package.integrity"),
    )
    expected_tarball = (
        "https://registry.npmjs.org/@phosphor-icons/core/-/"
        f"core-{package.version}.tgz"
    )
    if package.name != "@phosphor-icons/core" or package.tarball != expected_tarball:
        fail("package name or tarball does not match the locked Phosphor version")
    if not package.integrity.startswith("sha512-"):
        fail("package.integrity must use sha512 SRI")

    icons_value = root["icons"]
    if not isinstance(icons_value, list) or not icons_value:
        fail("icons must be a non-empty array")
    icons: list[IconLock] = []
    seen_outputs: set[Path] = set()
    for index, raw_icon in enumerate(icons_value):
        field = f"icons[{index}]"
        icon_value = require_object(raw_icon, field)
        if set(icon_value) != {
            "sourceSet",
            "resource",
            "asset",
            "sourceSha256",
            "outputSha256",
        }:
            fail(f"{field} fields do not match the schema")
        icon = IconLock(
            source_set=require_string(icon_value["sourceSet"], f"{field}.sourceSet"),
            resource=require_string(icon_value["resource"], f"{field}.resource"),
            asset=require_string(icon_value["asset"], f"{field}.asset"),
            source_sha256=require_sha256(icon_value["sourceSha256"], f"{field}.sourceSha256"),
            output_sha256=require_sha256(icon_value["outputSha256"], f"{field}.outputSha256"),
        )
        if icon.source_set not in SOURCE_SETS:
            fail(f"{field}.sourceSet is unsupported")
        if RESOURCE_PATTERN.fullmatch(icon.resource) is None:
            fail(f"{field}.resource is not an Android Phosphor resource name")
        if ASSET_PATTERN.fullmatch(icon.asset) is None:
            fail(f"{field}.asset is not a supported Phosphor SVG path")
        if icon.output_path in seen_outputs:
            fail(f"duplicate output {icon.output_path.relative_to(REPO_ROOT)}")
        seen_outputs.add(icon.output_path)
        icons.append(icon)
    return package, tuple(icons)


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def check_outputs(package: PackageLock, icons: tuple[IconLock, ...]) -> None:
    failures: list[str] = []
    expected_paths = {icon.output_path for icon in icons}
    for icon in icons:
        try:
            actual = sha256(icon.output_path.read_bytes())
        except OSError:
            failures.append(f"missing {icon.output_path.relative_to(REPO_ROOT)}")
            continue
        if not hmac.compare_digest(actual, icon.output_sha256):
            failures.append(f"drifted {icon.output_path.relative_to(REPO_ROOT)}")

    for source_set in SOURCE_SETS:
        drawable_dir = REPO_ROOT / "app" / "src" / source_set / "res" / "drawable"
        for path in drawable_dir.glob("ic_ph_*.xml"):
            if path in expected_paths:
                continue
            try:
                generated = GENERATED_MARKER in path.read_text(encoding="utf-8")
            except OSError:
                generated = False
            if generated:
                failures.append(f"stale {path.relative_to(REPO_ROOT)}")

    if failures:
        fail("icon drift detected:\n  " + "\n  ".join(sorted(failures)))
    print(
        f"Phosphor icon drift check passed "
        f"({len(icons)} drawables, {package.name}@{package.version})"
    )


def fetch_package(package: PackageLock) -> bytes:
    try:
        with urllib.request.urlopen(package.tarball, timeout=30) as response:
            archive = response.read()
    except OSError as error:
        fail(f"package download failed: {error}")
    expected = package.integrity.removeprefix("sha512-")
    actual = base64.b64encode(hashlib.sha512(archive).digest()).decode("ascii")
    if not hmac.compare_digest(actual, expected):
        fail("downloaded package does not match locked sha512 SRI")
    return archive


def render_drawable(icon: IconLock, version: str, svg: bytes) -> bytes:
    try:
        root = ElementTree.fromstring(svg)
    except ElementTree.ParseError as error:
        fail(f"{icon.asset} is invalid XML: {error}")
    paths = [
        element.attrib["d"]
        for element in root.iter()
        if element.tag.endswith("path") and "d" in element.attrib
    ]
    if not paths:
        fail(f"{icon.asset} contains no path data")
    body = "\n".join(
        "    <path\n"
        '        android:fillColor="#FF000000"\n'
        f'        android:pathData="{escape(path, {chr(34): "&quot;"})}" />'
        for path in paths
    )
    icon_name = icon.resource.removeprefix("ic_ph_").replace("_", "-")
    return (
        f"<!-- Phosphor {icon_name} v{version} (MIT). {GENERATED_MARKER} -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="24dp"\n'
        '    android:height="24dp"\n'
        '    android:viewportWidth="256"\n'
        '    android:viewportHeight="256">\n'
        f"{body}\n"
        "</vector>\n"
    ).encode("utf-8")


def generate(package: PackageLock, icons: tuple[IconLock, ...]) -> None:
    archive = fetch_package(package)
    expected_paths = {icon.output_path for icon in icons}
    try:
        package_tar = tarfile.open(fileobj=io.BytesIO(archive), mode="r:gz")
    except tarfile.TarError as error:
        fail(f"locked package is not a readable tarball: {error}")
    with package_tar:
        for icon in icons:
            member_name = f"package/{icon.asset}"
            try:
                source_file = package_tar.extractfile(member_name)
            except KeyError:
                source_file = None
            if source_file is None:
                fail(f"locked package is missing {icon.asset}")
            source = source_file.read()
            if not hmac.compare_digest(sha256(source), icon.source_sha256):
                fail(f"{icon.asset} does not match its locked SHA-256")
            output = render_drawable(icon, package.version, source)
            if not hmac.compare_digest(sha256(output), icon.output_sha256):
                fail(f"generated {icon.resource}.xml does not match its locked SHA-256")
            icon.output_path.parent.mkdir(parents=True, exist_ok=True)
            icon.output_path.write_bytes(output)
            print(f"wrote {icon.output_path.relative_to(REPO_ROOT)}")

    for source_set in SOURCE_SETS:
        drawable_dir = REPO_ROOT / "app" / "src" / source_set / "res" / "drawable"
        for path in drawable_dir.glob("ic_ph_*.xml"):
            if path in expected_paths:
                continue
            try:
                generated = GENERATED_MARKER in path.read_text(encoding="utf-8")
            except OSError:
                generated = False
            if generated:
                path.unlink()
                print(f"removed {path.relative_to(REPO_ROOT)}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify checked-in drawables from the lock without network access",
    )
    arguments = parser.parse_args()
    package, icons = load_lock()
    if arguments.check:
        check_outputs(package, icons)
    else:
        generate(package, icons)


if __name__ == "__main__":
    main()
